lambdaclass/champions_of_mirra

server/lib/dark_worlds_server/engine/runner.ex

Aims to make the `Runner` module clearer. The main idea is to have a single endpoint for each action.
- Merged `skill/attack` & `move` endpoints together.
- Eliminated multiple declarations of some endpoints (moved logic from guards to regular conditionals/helper functions)
- `all_characters_set?`
- `character_selection_time_out`
- `check_player_amount`
- `join`
- Merged `next_round` & `last_round` endpoints
- Abstracted broadcasts to `DarkWorldsServer.PubSub `
Possible improvement: on [`character_selection_time_out`](https://github.com/lambdaclass/dark_worlds_server/pull/375/files#diff-76737aa21f7d56595726b042cb812cb7e4d190810c1d6f8329930a6d351f0291R470) I didn't want to assume `state` always had a `selected_characters` key. If it does, this code could be slightly improved.

Refactor Engine.Runner module

---

server/lib/dark_worlds_server/engine/runner.ex

We were not getting the tickrate from the game config, instead we were always using the default one.

Fix runner tickrate

---

client/Assets/Prefabs/PlayerBot.prefab
client/Assets/Prefabs/UI/SpawnBotButton.prefab
client/Assets/Scripts/PlayerMovement.cs
client/Assets/ThirdParty/DogKnight/Animator/DogControl.controller
server/lib/dark_worlds_server/engine/bot_player.ex

Bots: add logic to attack players

---

client/Assets/Scripts/LobbyConnection.cs
client/Assets/Scripts/SocketConnectionManager.cs
client/Assets/Scripts/UI/UICharacterItem.cs

closes #489
The bug happens when we select a character too quickly that the game didn't even connected to the server, thus, our character selection breaks and the entire game too.
In this PR, I introduced a new function called `isConnectionOpen` in the `SocketConnectionManager`, maybe in the future we can use that function for loading screens.

Fix character selection bug

---

client/Assets/Scenes/BackendPlayground.unity
client/Assets/Scripts/LobbyManager.cs
client/Assets/Scripts/SocketConnectionManager.cs
server/lib/dark_worlds_server/engine/runner.ex

closes #491 
The main reason we were not closing the game when we should, is because we were not closing the web socket connections for each player. This PR adds that feature in the client and fix a bug in the runner where we were not setting properly the game status after the game finished

Close the game after all players left the game

---

client/Assets/Scenes/Lobby.unity
client/Assets/Scripts/LobbyManager.cs
client/Assets/Scripts/PlayerMovement.cs

There was a problem in the Update() method of the LobbyManager class, that made that the non-host players were kicked out of the character selection scene.

Fix: Lobby manager update

---

client/Assets/Models/Characters/Minotauro-Material.mat
client/Assets/Models/Characters/Minotauro-Material.mat.meta
client/Assets/Models/Characters/Muflus-Base.fbx.meta
client/Assets/Prefabs/Characters/Muflus.prefab
client/Assets/Prefabs/OverlayShader.prefab
client/Assets/Resources/OverlayDamageShader.shadergraph
client/Assets/Resources/OverlayDamageShader.shadergraph.meta
client/Assets/Scripts/OverlayEffect.cs
client/Assets/Scripts/PlayerFeedbacks.cs
client/Assets/Scripts/UI/PlayerItem.cs
client/Packages/manifest.json
client/Packages/packages-lock.json
client/ProjectSettings/QualitySettings.asset
client/ProjectSettings/VFXManager.asset

This PR :
- fixes the bug in main where the damage overlay shader is not displayed. 
- Adds the "YOU" label missing in the player list.
- Change the Android Render Pipeline to URP ( It was missing in the quality settings )
closes #529 
closes #524

Fix damage overlay shader and more

---

client/Assets/Scripts/EventsBuffer.cs
client/Assets/Scripts/PlayerMovement.cs
client/Assets/Scripts/SocketConnectionManager.cs
server/lib/dark_worlds_server/engine/runner.ex

This PR fixes the following problems:
- If the client receives and event where it has to render skill feedbacks, since the frame rate goes faster than the server updates, it ends executing the feedback multiple times. Although this is not visible because the animations has blocking states. We're fixing this by adding the last server timestamp which the client saw
- There was an error where we were sending again the start game message to the client, this was caused by the `character_selection_time_out` function in `runner.ex` that was not checking that the game has finished.
- There was an error where the last tick was not being sent with effects like the Poison, Shrink zone o projectiles.
- The shrink zone was still executing in after the game has finished because we were never checking …

Last timestamp seen and bugs

---

client/Assets/Scripts/EventsBuffer.cs

When getting the previous and next events to check for movement, we were using time (specifically, a hardcoded 30 ms) to try to index into the next and previous elements of the buffer. This can be a problem because updates are not guaranteed to always be 30 ms apart, for a variety of reasons.
Instead, this PR changes things so we simply get the next and previous events with their index. Events are guaranteed to be ordered so this is enough

Small fix to interpolation

---

client/Assets/Scripts/LobbyManager.cs

This Fix the console errors where playbutton.
PD : We should refactor the use of lobbyManager removing it from the pause splash , chatacter selection.

Fix missing prefab in lobbyManager

---

client/Assets/Prefabs/UI/LobbyItem.prefab
client/Assets/Scripts/LobbiesManager.cs
client/Assets/Scripts/UI/LobbiesListItem.cs

This PR removes the instances of `LobbiesManager` that we had in the `LobbyItem`.
Now we have an Instance of `LobbiesManager` so each `lobbyItem` intanciate can access to the methods. In our case we need `ConnectToLobby(string idHash)`
closes #723 
closes #663

Lobbies Refactor

---

.github/workflows/aws-staging-deploy.yml
.github/workflows/aws-testing-deploy.yml

This PR aims to enhance the security of the GitHub Actions workflow that involves SSH connections.
Previously, we had been using the `StrictHostKeyChecking=no` option to bypass host key verification, which introduced potential security risks.
The problem with using `StrictHostKeyChecking=no` is that it disables the verification of the remote server's identity, leaving us susceptible to man-in-the-middle attacks. To address this, we've implemented a more secure approach:
We are now using the `ssh-keyscan` command to fetch the public keys of the remote.
By appending the fetched keys to the `~/.ssh/known_hosts` file, we populate it with the host's public keys.
This eliminates the need for `StrictHostKeyChecking=no` and allows the SSH client to automatically verify the server's identity by …

Hardened SSH security in GitHub Actions.

---

client/Assets/Scripts/AimDirection.cs
client/Assets/Scripts/CustomInputManager.cs
client/Assets/Scripts/UI/SafeZone.cs

This PR solves issue #874 
To check is this was solved I made a quick video to follow:
Basically, change the cone, skillRange or terrainZone material and keep then in the inspector. When running the game they should no longer change.
This is how it was working before:
https://github.com/lambdaclass/curse_of_myrra/assets/82987608/d29008b1-cf4c-4690-994a-970ab9b81c3b
This is how it's supposed to work:
https://github.com/lambdaclass/curse_of_myrra/assets/82987608/33fa5cc5-4e96-4dd0-b28d-058e9e1d8b4b

Fix unwanted material update

---

client/Assets/Prefabs/Camera/CameraUI.prefab
client/Assets/Prefabs/Camera/LobbiesCameraUI.prefab
client/Assets/Prefabs/UI/ErrorCanvas.prefab
client/Assets/Scenes/Lobbies.unity
client/Assets/Scripts/LobbiesManager.cs
client/Assets/Scripts/UIManager.cs

This PR solves issues #664 and #779 
It optimizes the way we refresh our lobbies list and changes the buttons styles (in lobbies scene) to fix ui and ux problems.
Issues to check if they were solved:
- Hold your finger in the Refresh button. It should no longer refresh constantly. Instead, it should refresh when you stop pressing on it.
- If you press the Refresh button it should no longer toggle as much between the empty list indicator and the lobbies. Instead it should show either one or the other until your next refresh. 
_Two things to take into account: now it may not show you a lobby if it took too long to fetch it. That is expected and it works like that in other games too. In that case you should refresh again; If you spam the Refresh button it may occur that a lobby list is shown …

Refresh refactor

---

client/Assets/Prefabs/Characters/Uma.prefab

Closes #925 
In Uma's Character Orientation 3D component, Forced Rotation was disabled, causing problems when trying to rotate the character without moving it first at the beginning of a new match.

Enable Uma's forced rotation

---

client/Assets/Scripts/Battle.cs

The problem:
- The Danger zone UI sometimes was not appearing correctly.
What happened ?
- When someone die a method called `SetPlayerDead` in `Battle.cs` called  `CustomGUIManager.DisplayZoneDamageFeedback(false);` causing the bug
The Fix:
- We only want to desactivate the zone effects if we are dead and it is in our client, so:
```
if (SocketConnectionManager.Instance.playerId == ulong.Parse(playerCharacter.PlayerID))
{
CustomGUIManager.DisplayZoneDamageFeedback(false);
}
```
closes #1047

Fix Danger zone UI

---

server/lib/dark_worlds_server/engine/bot_player.ex

This pr is part of #709 
The bots should pick a random location in the playable area (inside the zone) and walk to it now, they can get distracted if they come across a player of loot crate on their way
To pick their next wander position the posible destinations should meet the next requirements:
- Be inside of the bot visibility zone
- Be inside of the board
- Be inside of the safe zone
i'll attach some examples of possible destinations:

Add bot wandering

---

.github/pull_request_template.md

Sometimes the PRs descriptions don't give you enough context or explain more than it should.
With a template we standardize what we want to tell to the reviewers about the PR.

Add template for pull-requests descriptions

---

client/Assets/Scenes/Battle.unity
client/Assets/Scripts/CustomLevelManager.cs

Problem
- When you spawn a bot, Unity crashes because the prefabs are not loaded.
Solution
- Add the prefabs

Fix bot spawn

---

client/Assets/Scripts/Battle.cs
client/Assets/Scripts/Projectiles/ProjectileHandler.cs
client/Assets/Scripts/SocketConnectionManager.cs

Closes #1086 
When shooting H4ck's basic attack (would've happened with any projectile) for a frame, those projectiles appeared in the center of the map, this is the position of the BattleManager game object that holds the ProjectileHandler script, which assigned it's own position, and by extension, BattleManager's position, to the projectiles on the spawn frame.
- Modified the UpdateProjectiles method in `Battle.cs` to calculate `backToFrontPosition`, whether the projectile already existed on the client or not.
- Added the `initialPosition` parameter to the `InstantiateProjectile` method inside `ProjectileHandler.cs` and assigned it as the `transform.position` of the pooled projectile before setting it as active.
- Pased the aformentioned `backToFrontPosition` variable to the …

[GH-1086] Fix projectiles appearing in the center of the map at spawn frame

---

client/Assets/Prefabs/Camera/CameraUI.prefab
client/Assets/Prefabs/Camera/LobbyCameraUI.prefab
client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
client/Assets/Scenes/Battle.unity
client/Assets/Scenes/MainScreen.unity

When redoing the game flow the sound in battle was broken
Also, the death splash exit buttons are not working
The main scene needed the sound manager prefabs that were in deprecated lobbies scene
I also fixed exit buttons

fix sounds

---

client/Assets/Scripts/Battle.cs
client/Assets/Scripts/ClientPrediction.cs
server/lib/dark_worlds_server/engine/bot_player.ex
server/lib/dark_worlds_server/engine/engine_runner.ex
server/lib/dark_worlds_server/matchmaking/matching_coordinator.ex

We are missing the timestamps for the players, so we are unable to clean the client prediction updates queue.
- fix the timestamps players key
- clean some code
- separate bots process tick from server game tick

fix backend not sending timestamps properly

---

client/Assets/Scripts/UI/DeathSplash/DeathSplashManager.cs
server/lib/dark_worlds_server/engine/engine_runner.ex
server/lib/dark_worlds_server_web/websockets/lobby_websocket.ex

Closes #1126 
The game should terminate without errors to prevent weird behavior of the game.
- [Add terminate/3 clause in LobbyWebsocket to show log info instead of an error](https://github.com/lambdaclass/curse_of_myrra/pull/1137/commits/7106011fc42b7ff8ef134d67c5ffd1be6156110e)
- [Save alive players in every tick and pick one of them as winner when the end game condition is met](https://github.com/lambdaclass/curse_of_myrra/pull/1137/commits/5e292ef3e7ca55980fcfbf0ad469a45cbc1d1baa)
- [Fix winner player final place in game when all players are dead](https://github.com/lambdaclass/curse_of_myrra/pull/1137/commits/3faf2a27c086f6d8af7141cfd9af956d327cf526)
- Tested alone dying by the zone.
- Tested with my phone as a second player:
- Both dying at the same time by the zone.
- Killing each …

[GH-1126] Fix end game backend bugs

---

client/ProjectSettings/EditorBuildSettings.asset

Some builds branched from main do not work because they are missing the main scene in the editor builder settings
This PR adds main to the editor build settings

Add main to editor build settings

---

client/Assets/Prefabs/HealthBar.prefab

There was a reference error preventing the user to start a match as the new muflus
I re-referenced the foreground bar in the MMProgressBar component

Fix Foreground bar from health bar

---

client/Assets/Prefabs/Camera/CharacterInfoCameraUI.prefab
client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
client/Assets/Scenes/MainScreen.unity

Closes #1167
The character illumination on the main screen wasn't adequate for the new Muflus implementation, which sets the new standard for characters in terms of materials.
The other characters are slightly brighter than they should be, but they will be removed or changed in upcoming updates.
- Updated main screen character lightning.
On the main screen, Muflus should be illuminated as it is in the reference.

Improved main screen character lightning

---

client/Assets/Prefabs/Managers/BattleManagers.prefab
client/Assets/Scripts/CustomLevelManager.cs

Closes #1179 
We didn't want the battle music so the main screen one keeps playing though all the gameplay.
- Removed the BattleBackgroundMusic object from inside the BattleManagers prefab which would start playing the battle music when entering the corresponding scene.
- Deleted the backgroundMusic field and the code that stopped all other sounds from playing and used this reference to reproduce the battle music in the CustomLevelManager script.
Played the game normally checking that when entering a game the main screen music keeps playing and no other music overlaps it.
No tests where added or updated.

Disable battle music

---

client/Assets/AddressableAssetsData.meta

This file appears for every dev with changes only by opening the project. Apparently it was not properly saved in this [PR](https://github.com/lambdaclass/curse_of_myrra/pull/1132/files) adding the load tests
I added those changes to fix that for everyone

Addressable assets data changes

---

client/Assets/Prefabs/Characters/UICharacters/Muflus.prefab

The rotation for muflus was not rotating properly
Muflus model was centered to make the rotation be at the character's center

Muflus anchor

---

client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Melee.asset

Now all skills should have input types direction or area, resulting in joystick inputs.
This PR implements that. We are missing indicators but they are coming in a future PR

Muflus direction skill

---

client/Assets/Scripts/CustomLevelManager.cs

Closes #1197
Can't test load tests while playing a game on unity (if my client gets matched with the load test's clients)
- [get ids from gamePlayers instead of simple counter](https://github.com/lambdaclass/curse_of_myrra/pull/1198/commits/c1f9469f5af80c6de83820bde03b6e119690c159)
Tested locally by starting a new game and quickly running a round of the load test (I mention the steps on the issue)

[GH-1197] get ids from gamePlayers instead of simple counter

---

client/Assets/Scripts/CustomLevelManager.cs

The game had the problem that in LOW/MID devices it insta crash at the beginning of the battle.
You can see all the iteration steps in: 
https://www.notion.so/lambdaclass/Client-performance-benchmark-template-15145122c5464cc8870c02b24052aa81?pvs=4
After a huge debug we found that the cause of these crashes were the following code inside `CustomLevelManager`, `CameraCinematic` method
```
Utils
.GetAlivePlayers()
.Where(player => player.Id != playerId)
.ToList()
.ForEach(
el =>
StartCoroutine(
Utils.GetCharacter(el.Id).characterBase.activateSpawnFeedback(false)
)
);
```
Tested in the following mobiles phones:
`Tested on Xiomi redmi note 9s:`
Before: Insta Crash
After: Playable at 32 FPS the whole game
`Tested on Moto Edge 30 neo:`
Before: Insta Crash
After: Playable at 40 FPS the whole game …

PERFORMANCE ITERATION 3 - Fix insta game crash on low/mid devices

---

client/Assets/ArabanV2/Araban/Tents.mat
client/Assets/ArabanV2/Araban/desert-sand_graph_0/NewLayer.terrainlayer
client/Assets/ArabanV2/Materials/desert-path_graph_0/NewLayer.terrainlayer
client/Assets/ArabanV2/Prefabs/NewLayer.terrainlayer
client/Assets/ArabanV2/Textures/Lava rocks diffuse.png.meta
client/Assets/ArabanV2/Textures/Lava rocks lava difusse.png.meta
client/Assets/ArabanV2/Textures/NewLayer 1.terrainlayer
client/Assets/ArabanV2/Textures/NewLayer 2.terrainlayer
client/Assets/ArabanV2/Textures/NewLayer.terrainlayer
client/Assets/ArabanV2/Textures/desert_path_Base_Color.png.meta
client/Assets/ArabanV2/Textures/desert_sand_Base_Color.png.meta

Araban was looking too shiny on mobiles build. This fix that.
Changed Channel remapping of each texture in the terrain paint textures. 
- Mettalic to 0
- AO to 0
- Smoothness to 0
Removed the mettalic map from the tents material
Make a build in any phone and terrain materials should not be shinning anymore.

Fix Araban lights

---

client/Assets/LobbyPlayerCounter.cs
client/Assets/Scripts/LobbyConnection.cs

The new lobby player counter was too unnatural since it would jump from 1 to 10 in the last second
Added new repeating method to the lobby connection module that add a random amount to a new field to hold a fake count of players
join a lobby in any server
No test were added

Simulate player joining to lobby

---

client/Assets/Scripts/Battle.cs
client/Assets/Scripts/EventsBuffer.cs
client/Assets/Scripts/Game/Player.cs
client/Assets/Scripts/Messages.pb.cs
client/Assets/Scripts/SkillAnimationEvents.cs
client/Assets/Scripts/Skills/Skill.cs
communication/messages.proto

We needed to separate the duration of actions from each other in order to render properly the animations.
- Add the necessary fields to protobuf.
- Battle and Skills files refactor, now we have tuples instead of enums.
- Start animation if the duration is grater than 0.
With 2 human players and against bots.

Implement action tracker

---

client/Assets/Prefabs/Camera/CameraUI.prefab

During playtest the team decided it was better for the metrics display to be on by default
This PR shows the metrics by default. This can be changed by the player going to `Settings > dev section > Toggle metrics`

Restore metrics

---

client/Assets/Prefabs/CharacterCard.prefab

This prefab if open by a dev was changing to the oposite value of `m_PresetInfoIsWorld` from it was set to. This was because of a component that should not have been applied there called `CanvasScaler`
This PR deletes that component and fixes the bug. To test this works correctly I recommend starting a match and checking the health bars and names from every player are not distorted when moving them around
To test this worked the reviewer should be able to open the CharacterCard prefab and have no changes made by this

Bug fix for character card prefab

---

client/Assets/Scripts/Battle.cs
client/Assets/Scripts/CustomLevelManager.cs
client/Assets/Scripts/Game/GameState.cs
client/Assets/Scripts/Game/Item.cs
client/Assets/Scripts/Game/Position.cs
client/Assets/Scripts/Loot.cs
client/Assets/Scripts/SocketConnectionManager.cs
client/Assets/Scripts/UI/SafeZone.cs
client/Assets/Scripts/Utils/Utils.cs

This is part of the work to make the client up to date with regards to backend representation
- Start using items game information from the new game state version
- Stop usage of old Loot protobuf class and use the internal representation Item class
Locally, nothing should have changed with regards to UX
This PR depends on https://github.com/lambdaclass/game_backend/pull/123 for some minor fixes to be able to decode the new game state

Start using items from new game state and stop protobuf class usage

---

client/Assets/Scripts/GameServerConnectionManager.cs
client/Assets/Scripts/Messages.pb.cs
messages.proto

On joining a game receive the game configuration 
- Modify protobuf to have a `GameEvent` compose of 2 events (for now), `joined` and `update`
- Modify websocket handler to behave differently based on game event
To test this PR you will need to run the backend on https://github.com/lambdaclass/mirra_backend/pull/171

Receive  game configuration on start

---

client/Assets/Scenes/TitleScreen.unity

In main the error container is deactivated therefore when there is an error connection the game thrown a null reference error

Error prefab fix

---

client/Assets/Scripts/CustomLevelManager.cs
client/Assets/Scripts/GameServerConnectionManager.cs
client/Assets/Scripts/ServerConnection.cs

Camera ins't being assigned to the players properly. There are cases where your camera is following a different player than the one you move.
Restore commented code to achieve the correct behavior.
I played several games with 2+ players (phone, browser tabs, pc).

Fix camera following player in multiplayer games

---

client/Assets/Scenes/TitleScreen.unity
client/Assets/Scripts/ServerConnection.cs

We want to show live updates of the lobby getting filled
For now this only re-enables the fake counter we had
Run the game

Re-enable lobby counter

---

client/Assets/Prefabs/Characters/H4ck.prefab

H4ck `characterFeedbacks` script was missing the reference of the `deathFeedback` prefab breaking the game.
- Start a game with 2 h4cks with this branch https://github.com/lambdaclass/mirra_backend/pull/211 and change game_update.ex character name from muflus to h4ck.
- Kill 1 h4ck
- No errors should be deplayed in the unity console.

Add H4ck´s missing death prefab reference

---

client/Assets/Animations/Hack/Defeated.anim
client/Assets/Animations/Hack/H4ckUIController.controller
client/Assets/Animations/Hack/Victory.anim
client/Assets/Prefabs/Characters/H4ck.prefab
client/Assets/Scripts/UI/EndGame/EndGameManager.cs

Closes #1354 
We had some erorrs in the client side.
- Fixed h4ck mising damage Feedback prefab
- Fixed endSplash when get killed by the zone
- Fixed h4ck endplash animations making them loop.
Start a game with h4ck (Select it in the characterinfo screen). 
Go to the danger zone and get killed. 
Yo should see the damage feedback (Red and screen shake) then the animations of defeat and victory must be in loop. 
And in the killedby section (endsplash) the image of the dangerzone should be shown.
No errors in the console.

Simple client fixes

---

client/Assets/Scripts/CustomLevelManager.cs
client/Assets/Scripts/Messages.pb.cs
client/Assets/Scripts/UI/EndGame/EndGameManager.cs
messages.proto

Instantiate the correct character for each player.
Start a game with 2 players. With one select muflus and the other h4ck. When the game start you should see 1 muflus and 1 hack.
Test with https://github.com/lambdaclass/mirra_backend/pull/233

instantiate correct character

---

client/Assets/Scripts/CustomLevelManager.cs

Closes #1403
When the health of the player surplus 100 the client health bar is not displaying the damage. (but it is happening)
Set Initial health and max health on player creation.

Fix health bar not reducing on damage

---

client/Assets/Prefabs/Camera/CameraUI.prefab
client/Assets/Prefabs/Characters/H4ck.prefab
client/Assets/Prefabs/Characters/Muflus.prefab
client/Assets/Prefabs/Characters/Uma.prefab
client/Assets/Prefabs/Feedbacks/DamageFeedback.prefab
client/Assets/Prefabs/HealthBar.prefab
client/Assets/Scripts/CharacterFeedbacks.cs

Closes #1344 
Improve damage feedback from a instant fash to a fade.  The main difference here is when the red screen disappear. Now it is not instantly and is more smooth.
https://github.com/lambdaclass/curse_of_mirra/assets/62818001/e4eb87f3-f24d-4cf2-88ca-efa8f533e1c0
**Ignore the pink squares. I do not have loaded the assets.**
Change DamageFeedback prefab and add fader object to CameraUI
Test with this backend branch : https://github.com/lambdaclass/mirra_backend/pull/244
Start a game and receive damage.
Disclaimer: The damage when you receive it from the danger zone could be too much. This is because we are dealing the damage from the backend in every tick. We either left this until the backend is fixed or make a temporary workaround in the client.

Improve Damage Feedback

---

client/Assets/Scripts/CustomLevelManager.cs

The vfx was showing wrong. Only the vfx of what character you selected was being displayed.  With this each character skills are set correctly.
Play a game with 2 or more players. You should see each character vfx correctly

Fix showing wrong vfx

---

client/Assets/Prefabs/Camera/CameraUI.prefab

The team thinks it's better to have the dash skill input on the top
This PR swaps skill 2 and skill 3 (dash)'s positions

Swap input 2 and 3 positions

---

client/Assets/Scripts/Messages.pb.cs
messages.proto

Update `messages.proto` with the new fields containing the information about damage on each tick
Test with https://github.com/lambdaclass/mirra_backend/pull/263

Receive per tick damage info

---

client/Assets/Scripts/CustomLevelManager.cs

Player should spawn in their initial position (and not "walk" to it when the map is loaded).

Players spawn position fix

---

client/Assets/Scripts/CustomCharacter.cs

When the player dies the stamina indicator was not desactivated
Desactivate canvasholder wich includes both stamina and player card when player is dead.

Desactivate stamina on death

---

client/Assets/Prefabs/CharacterBase.prefab
client/Assets/Prefabs/Characters/H4ck.prefab

Raised character orientation game object to prevent terrain overlapping, especially the center circle.

Fixed orientation indicator overlapping

---

client/Assets/Scripts/Battle.cs

We were using backend positions to move projectiles. When you had some lag, you saw projectiles jumping from the previous position to the next one.
This PR solves that
Use frontend values to calculate the next position.
Use H4ck and shot

Use frontend values to calculate projectiles position

---

client/Assets/Scripts/Battle.cs
client/Assets/Scripts/CustomCharacter.cs
client/Assets/Scripts/CustomLevelManager.cs

The player's direction was wrong because added a threshold to the magnitude of the movement between frames.

Fix direction when moving

---

client/Assets/Prefabs/Camera/CameraUI.prefab
client/Assets/Scripts/UI/PrepareForBattleAnimations.cs

Until issue #1511 is solved
The smoke effect was outdated
This PR hides the violet smoke effect until this animation is updated.
The effect has been hidden and not deleted to save time during the reimplementation process.
Start a match and play close attention to the survive text. Since this is not the final look and a refactor is coming soon I recommend reviewing if this doesn't bother the eye so much until this is solved

Hide smoke effect in Survive text

---

client/Assets/Prefabs/AimDirection.prefab
client/Assets/Prefabs/Camera/CameraUI.prefab
client/Assets/Prefabs/CharacterBase.prefab
client/Assets/Prefabs/CharacterCard.prefab
client/Assets/Prefabs/Feedbacks/DamageFeedback.prefab
client/Assets/Prefabs/Feedbacks/HitFeedback.prefab
client/Assets/Prefabs/HealthBar.prefab
client/Assets/Prefabs/Hitbox.prefab
client/Assets/Prefabs/Player Name.prefab
client/Assets/Prefabs/PowerUps.prefab
client/Assets/Prefabs/SkillRange.prefab
client/Assets/Prefabs/StaminaCharges.prefab
client/Assets/Prefabs/UI/DeathSplash.prefab
client/Assets/VFX-Tools/PIngle_VFX/AimIndicator/AimIndicator.prefab
client/Assets/VFX-Tools/PIngle_VFX/Arrow/ArrowPlane.prefab
client/Assets/VFX-Tools/PIngle_VFX/SectorOutliner/SectorOutliner.prefab
client/Assets/VFX-Tools/PIngle_VFX/Surface/Surface.prefab
client/ProjectSettings/TagManager.asset

Closes #1532 
The UI in game was changing their color because it was affected by post processing
The camera layers were wrong so that was fixed
A new layer called "NoPostProcess" was created and applied to all desired elements we don't want to be affected by the post processing component in game
Check:
- stamina indicators
- orientation indication of player
- player name
- health bar
- skill indicators
The reason for not applying that to the feedbacks is I believe the postprocessing there makes the feedback feel more as if they were part of the world and character instead of being clearly in another layer.
In main you can see this:
https://github.com/lambdaclass/curse_of_mirra/assets/82987608/93a42be3-b212-4f59-a808-08dd8206c35a
Take into account you can't see the fix in the scene but it …

PostProcessing not affecting UI in game

---

client/Assets/Materials/Characters/Uma/Updated/Uma_txt.mat

In both main and character info screens Uma's model was only rendering the front face of the material. This resulted in the following error inside her sleeves: 
Fixed the material config

Fix uma's material render face

---

client/Assets/Scripts/Battle.cs
client/Assets/Scripts/PlayerControls.cs

We felt like the player slides when changing direction.
We were using the joystick value to calculate the character rotation in every frame.
On the other hand, we only accept movement every 30ms.
So the rotation was out of phase with the movement.
We did 2 changes here:
- Add a forced movement message to the backend every 500ms.
- Use the player direction to calculate the character rotation instead of the joystick value. 
Playing with muflus in several servers.

Fix character rotation

---

client/Assets/Scripts/UI/PrepareForBattleAnimations.cs

Closes #1601 
The prepare for battle animation was still playing even when the gameStart countdown from backend already finished. 
Adjust times, and coroutines exit statement. 
Start different games, corroborate all of them starts in the correct time. You can check this with the danzer zone timer in the matchStats container. It should appear as 35 seconds (That is the value it has in the config)

Fix countdown time

---

client/Assets/Animations/Muflus/MuflusGameController.controller

Closes #1620 
Sometimes, if you continue moving after rolling, the animation stayed in the rolling state until you stopped moving.
- Fixed Muflus' animator flow.
- Playing in a distant server to force the conditions that lead to the error.
- Executing a roll while moving, the animation shouldn't get stuck.

Fixed Muflus' Roll animator flow

---

client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/Uma_skill1_Graph.vfx

Closes #1628 
We needed to modify Uma's Avenge VFXs delay to match the animation.
Added 4 new properties to handle each swing vfx delay.
Changing these properties values should cause the VFXs to spawn accordingly.

Added delay parameters for each vfx of Uma's Avenge skill

---

client/Assets/Animations/Hack/H4ckController.controller
client/Assets/Animations/Muflus/MuflusGameController.controller
client/Assets/Animations/Uma/UmaController.controller
client/Assets/Prefabs/VisualEffects/Muflus_Crush_0.prefab
client/Assets/ScriptableObjects/Skills/Uma/Uma_Avenge.asset

all basics animations are faster to make the game more responsive. 
relies on a [backend PR ](https://github.com/lambdaclass/mirra_backend/pull/398)too so this won't work on its own.

faster basic anims

---

client/Assets/Prefabs/Camera/CameraUI.prefab

Closes #1618 
The current button's sizes, positions and reposition features were making the UX worse rather than better
This PR:
- Increases the skill input sizes (except the basic) by 10%
- Moves the skill inputs to adjust the UX
- The reposition feature was removed for the basic button but is still applied for the left joystick
Build the game in a mobile and test the UX

Refactor skill buttons

---

client/Assets/Scripts/LobbyManager.cs
client/Assets/Scripts/MainManager.cs

Closes #1527 
Instead of adding a visual feedback for an unexpected behavior the button's use was updated.
The button now automatically sends the user to the lobby. This prevents the user from waiting in the main screen confused if the play button's action went through or not. Then the user waits for a match and players in the lobby (as expected)
Try using mobile data to emulate different types of server connection. Test all available servers including local an this should work as described.

Play game button

---

client/Assets/Prefabs/Projectiles/HackMultishot.prefab
client/Assets/Prefabs/Projectiles/Valtimer_Animatter_Projectile.prefab
client/Assets/Scripts/Projectiles/SkillProjectile.cs

Closes #1636
The field trailRenderer from the SkillProjectile class is not being used and it is causing Hack Slingshot prefab to be modified every time at leas one Hack is created for the battle. 
Deleted the unused field from the class.

[GH-1636] Fix bug in Hack Slingshot prefab

---

client/Assets/Scripts/CharacterFeedbackManager.cs
client/Assets/Scripts/Messages.pb.cs
messages.proto

This is part of a huge refactor around effects in the backend, for more information see https://github.com/lambdaclass/mirra_backend/pull/425
Updated protobuf and small change to use `Player.Effect` as a list intead of a map
Test with the backend PR

Receive Player.Effects as list instead of map

---

client/Assets/Prefabs/Managers/BattleManagers.prefab
client/Assets/Prefabs/Managers/VFXGraphPrewarmer.prefab
client/Assets/Prefabs/Managers/VFXGraphPrewarmer.prefab.meta
client/Assets/ScriptableObjects/VFXGraphHolder.asset
client/Assets/ScriptableObjects/VFXGraphHolder.asset.meta
client/Assets/Scripts/Utils/VFXGraphHolder.cs
client/Assets/Scripts/Utils/VFXGraphHolder.cs.meta
client/Assets/Scripts/Utils/VFXGraphPrewarmer.cs
client/Assets/Scripts/Utils/VFXGraphPrewarmer.cs.meta

Added VFX Graph prewarmer - a tool for compiling shaders from VFX Graphs at the beginning of the scene to avoid freezes during gameplay.
- added VFX Graph prewarmer
To test the tool, perform usual gameplay. At the beginning of the Battle scene, the console log will show information about shader compilation time.

[VFX] Added VFX Graph prewarmer

---

client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Antimatter_Casting.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Antimatter_Impact.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Blink_IN.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Blink_OUT.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Crush.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Leap_AOE.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Leap_Init.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Singularity_AOE.vfx

Reassembled VFX Graph assets to fix game crashes on some Android devices when spawning Muflus effects.
- reassembled VFX Graph assets for Muflus and Valtimer effects
It's a bug fix, so to test it, simply activate one of Muflus' skills on an Android device.

[VFX] Fix vfx graph crush on Muflus effects

---

client/Assets/Prefabs/Camera/CameraUI.prefab
client/Assets/Prefabs/UI/BattlePlayerCardContainer.prefab

Closes #1712 
The portraits were a bit stretched in the Y axis
Use the issues reference images to compare if the issue was solved

Fix portraits resolution

---

.github/pull_request_template.md

Closes #1738 
The current PR template is too big and asks for things we don't use. This causes developers to ignore the whole template making it counter productive.
Removed section "Test additions / changes", remove tasks for adding tests, added task for testing the whole game, moved to the bottom task of documentation because it is optional

[GH-1738] Updated PR template

---

client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Denial.asset
client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Flash.asset
client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Leap.asset
client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Rampage.asset
client/Assets/ScriptableObjects/Skills/Uma/Uma_Sneak.asset
client/Assets/ScriptableObjects/Skills/Uma/Uma_Veil.asset
client/Assets/ScriptableObjects/Skills/Valtimer/Valtimer_Antimatter.asset
client/Assets/ScriptableObjects/Skills/Valtimer/Valtimer_Singularity.asset
client/Assets/ScriptableObjects/Skills/Valtimer/Valtimer_Warp.asset

Closes #1734 
Some skill descriptions were outdated and didn't reflect the current skill of the characters. Added a full stop to the end of the descriptors that didn't have. Also, there was a typo in Valtimer's Dash title (wrap instead of warp)
Reviewed skill descriptor and title for all characters.
Build and go to char info screen and review all characters. **I did not try it in Android, it is important that while testing the PR someone does**

[GH-1734] Fix skill name and descriptions in char info

---

client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Antimatter_Casting.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Antimatter_Impact.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Blink_IN.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Blink_OUT.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Crush.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Dinner_Time.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Leap_AOE.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Leap_Init.vfx
client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_Singularity_AOE.vfx

Some vfx where being modifies when unity did the auto compile
This PR fixes this issue
Make sure you have the following settings:
To test this go to main branch, make sure you dont have any modifies files, and do a build. The modifies vfx should appear.
Then, do the same process in this branch. There should not be any vfx files affected

Fix modified vfx

---

client/Assets/Prefabs/Camera/CameraUI.prefab
client/Assets/Scripts/CharacterFeedbacks.cs
client/Assets/Scripts/InventoryUI.cs
client/Assets/Scripts/Loot.cs
client/Assets/VFX-Tools/Pingle_Tools/PingleCheatPanelItems.cs

Back [PR](https://github.com/lambdaclass/mirra_backend/pull/577)
There are two new items to be added:
- giant
- fake-item
giant has a bottle icon
fake item has a box icon
they both have the golden clock vfx until the final ones are done. I could also leave them without any vfx but it should be decided by our PM or TLs
This PR adds them to the client 
run locally the backend and delete all items except for the one that you want to test, to ensure the item picked is the one desired

Add giant and fake item to client

---

client/Assets/Scripts/UI/EndGame/EndGameManager.cs
client/Assets/Scripts/UI/KillFeedManager.cs

Backend PR https://github.com/lambdaclass/mirra_backend/pull/587
There was no indicators in the killfeed when a player was killed by the zone
This PR fixes that
block bots movements to ensure they die by the zone
back repo
in bot manager > game_socket_handler
comment out lines 29 and 30

Fix killed by zone indicators

---

client/Assets/Scripts/UI/PrepareForBattleAnimations.cs

Fix first movement.
Change time freezing player movement.
Start a game check if you can move in the moment the Battle init animation disappear.

Fix movement block in battle init

---

client/Assets/Scripts/DynamicFontAssetAutoClear.cs

The PR [Fix dynamic font assets changing version control](https://github.com/lambdaclass/champions_of_mirra/pull/1814) broke the capacity to build the application since one of the namespaces used in the new script isn't part of the core Android development environment in Unity.
Added `#if UNITY_EDITOR` conditional encapsulating the new script so it only runs on the Unity editor, and not when building.
To test this it's necessary to test all the steps from the previously referenced PR, try to make a build for your device and check that it's fully playable.

Fix AssetModificationProcessor namespace breaking build

---

client/Assets/Prefabs/ServersOptions.prefab
client/Assets/Scenes/TitleScreen.unity
client/Assets/Scripts/SelectServerIP.cs
client/Assets/Scripts/Utils/ServerUtils.cs

Currently in a client if you get a JWT for one server and then change servers the client will try to re-use that same JWT. In the case of Brazil and Europe it would work cause currently they share gateway server, but if you go from localhost to Europe then you face problems. Essentially when you try to go across gateway servers and have a JWT in your client 
- Extend `SelectServerIP` to change the gateway server to use and the PlayerPrefs key where the JWT for that server is stored
- Now `CUSTOM` expects 2 IPs, arena and server in a format `arena_ip gateway_ip` (notice the space, also gateway needs the http/https part)
- Extend `ServerUtils` to use the new information in `SelectServerIP`
- Small cleanup of unneeded `IP` prefabs
To test this play across servers without clearing PlayerPrefs …

Fix JWT issues when changing servers

---

client/Assets/Prefabs/UI/BattleSettingsSplash.prefab
client/Assets/Scenes/Battle.unity
client/Assets/Scripts/Battle.cs
client/Assets/Scripts/GameServerConnectionManager.cs
client/Assets/Scripts/Messages.pb.cs
client/Assets/Scripts/UI/Settings/BattleSettingsController.cs
messages.proto

> [!IMPORTANT]  
> This PR must be merged along with https://github.com/lambdaclass/mirra_backend/pull/693
Closes #1831 
We need a way to disable/enable the bots as pleased, for testing purposes.
- [Add new ToggleBots protobuf message](https://github.com/lambdaclass/champions_of_mirra/pull/1840/commits/86be3870a52de103eb80b086e4b7e015db0e92a3)
- [Add new ToggleBots button in battle settings controller](https://github.com/lambdaclass/champions_of_mirra/pull/1840/commits/c71e31b241589507d4417898fbf2e1240cf884df)
- [Add new ToggleBots button action in battle script and its websocket message](https://github.com/lambdaclass/champions_of_mirra/pull/1840/commits/68a38c3a15ae5a77415993dcf07faccc85fc7d52)
- [Add ToggleBots button to BattleSettingsSplash …

[GH-1831] Add toggle bots button

---

client/Assets/Materials/Araban Mats/Araban Floor.mat
client/Assets/Scenes/Battle/MainCamera Profile.asset
client/Assets/Textures/Araban/Floor/Araban_Floor.png.meta

The map color values were outdated and in need of an update
Run the game in both desktop and a mobile device. The floor asset should look like the images uploaded

Map value balance

---

README.md

Code completion wasn't working in visual studio code due to the C# extension version, this pr adds that configuration to the readme file

Include vscode extension configuration in readme
