lambdaclass/champions_of_mirra

- .github/workflows/ci.yml
> Remove deploy on merge

- server/Makefile
- server/load_test/lib/lobby_player.ex
- Fix load tests, they were broken because of out-of-date config.
- Follow the readme from the load test app
> Update load tests to read config

- client/Assets/Scenes/BackendPlayground.unity
Closes #384 
- Disable noise to remove camera shake. 
- Adjust Vertical FOV to zoom in the camera. 
- Adjust deadzone to make the camera move as soon as the character makes a movement.
> Camera adjustments

- client/Assets/Scripts/Messages.pb.cs
- client/Assets/Scripts/PlayerControls.cs
- client/Assets/Scripts/Skills/Skill.cs
- messages.proto
- server/lib/dark_worlds_server/communication/messages.pb.ex
- server/lib/dark_worlds_server/communication/proto_transform.ex
- server/lib/dark_worlds_server/engine/position.ex
- server/native/gamestate/src/game.rs
- server/native/gamestate/src/lib.rs
- server/native/gamestate/src/player.rs
- server/native/gamestate/src/projectile.rs
- server/native/gamestate/src/utils.rs
- server/rust_tests_app/native/rustler_test/src/game_state_test.rs
> Coordiantes refactor

- client/Assets/Scripts/PlayerMovement.cs
This PR includes a simple commit but it has a huge impact in the Unity FPS.
- PlayerLoop GPU usage reduced in 55%
- GC.Alloc called 189 times less
- PlayerMovement.Update CPU usage reduced in 5%
- Before
-
- After
-
> Fix Unity performance

- client/Assets/Scripts/UI/LeftMMTouchJoystick.cs
This PR enables the multitouch
> Multi touch enable

- client/Assets/Prefabs/Camera/CameraUI.prefab
- client/Assets/Prefabs/PlayerBot.prefab
- client/Assets/Scenes/BackendPlayground.unity
- client/Assets/Scripts/Messages.pb.cs
- client/Assets/Scripts/SocketConnectionManager.cs
- client/Assets/Scripts/SpawnBot.cs
- messages.proto
- server/lib/dark_worlds_server/communication/messages.pb.ex
- server/lib/dark_worlds_server/communication/proto_transform.ex
- server/lib/dark_worlds_server/engine/bot_player.ex
- server/lib/dark_worlds_server/engine/runner.ex
- server/load_test/lib/load_test/communication/messages.pb.ex
> Bot movement

- server/lib/dark_worlds_server/engine/runner.ex
- server/native/gamestate/src/projectile.rs
To test:
- Shoot near walls in a parallel position to them. the projectile shouldn't explode.
> Fix noreply bug. Fix projectiles near wall.

- client/Assets/Prefabs/Camera/CameraUI.prefab
This PR modifies the ping update interval, this is only a visual change
https://github.com/lambdaclass/curse_of_myrra/assets/67444519/bb300fae-42af-4336-900e-bc72f62b3f67
closes #549
> Update ping interval update

- client/Assets/Prefabs/PlayerBot.prefab
Closes #478
1. Start a new game and spawn one or more bots.
2. Kill one bot.
3. Verify that there isn't a sword left in the spot where the bot was positioned when it was killed.
> Remove DogPBR second sword

- client/Assets/Scripts/CustomInputManager.cs
This PR fixes the disabled styles when pressing but not using a joystick in the right panel
> [Bug fix] Right Joysticks

- client/Assets/Prefabs/UI/LobbiesButtons.prefab
- client/Assets/Prefabs/UI/PlayGameButton.prefab
Fix the issue #536 , disabling the button so players cant spam it
closes #536
> Fix spameable buttons in lobby

- client/Assets/Scenes/CharacterSelection.unity
- client/Assets/Scripts/LobbyManager.cs
- client/Assets/Scripts/PreloadSceneInUnity.cs
- client/Assets/Scripts/PreloadSceneInUnity.cs.meta
- client/Assets/Scripts/SocketConnectionManager.cs
This PR pre load the game Scene in backendplayground.
This is the only way i found to do the mencioned. It you now another please comment it in this PR!
closes #538
> Pre Load GameScene

- .github/ISSUE_TEMPLATE/🎨-design.md
> Update and rename 🎨-desing.md to 🎨-design.md

- client/Assets/Animations/Hack/HackController.controller
- client/Assets/Animations/Muflus/MuflusController.controller
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Aimshot.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Basic.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Dash.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Multishot.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Leap.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Melee.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Rage.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Roll.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Skill4.asset
- client/Assets/Scripts/SkillAnimationEvents.cs
- client/Assets/Scripts/Skills/Skill.cs
- client/Assets/Scripts/Skills/SkillInfo.cs
- server/native/gamestate/src/player.rs
Fixes:
- Client character "gets stuck" and can't perform any action.
- Enemy player character "gets stuck", although they still can play but the client doesn't see any animation.
How to test it:
- Players character shouldn't "gets stuck" anymore.
- It is recommended to test this in a server far away form the client, since these bugs didn't usually occur in a local environment or with low ping.
- The bugs were triggered mostly when a player tried to execute multiple skills very quickly.
https://github.com/lambdaclass/curse_of_myrra/assets/6811225/5adda863-b27e-413f-918b-054b880cff4b
> Animation bugs

- client/ProjectSettings/ProjectSettings.asset
This PR removes the vertical/portrait mode in mobile builds ( Android)
closes #437
> Remove portrait mode on mobile

- client/Assets/Prefabs/Characters/H4ck.prefab
- client/Assets/Prefabs/Characters/Muflus.prefab
- client/Assets/Prefabs/Characters/Uma.prefab
- client/Assets/Prefabs/Player.prefab
- client/Assets/Prefabs/PlayerBot.prefab
closes #658 
- Fix healthbar position and scale
- Fix player name in Uma model
> Fix healthbar and player name

- client/Assets/Scripts/PlayerMovement.cs
> Remove physical joystick

- server/native/gamestate/Cargo.lock
- server/native/gamestate/Cargo.toml
- server/native/gamestate/src/game.rs
- server/native/gamestate/src/player.rs
- server/rust_tests_app/native/rustler_test/Cargo.lock
Closes #571 #687 
To test it, choose any character, start a match against another player, and kill each other. Both the killfeed and the number of kills should work correctly.
> fix kill count

- client/Assets/Prefabs/VisualEffects/FireCircleFeedback_p.prefab
> Fixed unwanted Muflus's leap feedback loop

- client/Assets/Prefabs/Camera/CharacterSelectionCameraUI.prefab
- client/Assets/Scripts/UI/CharacterSelectionUI.cs
- client/Assets/Scripts/UI/ConfirmButtonHandler.cs
- client/Assets/Scripts/UI/ConfirmButtonHandler.cs.meta
- client/Assets/Scripts/UI/UICharacterItem.cs
This PR:
- Fixes scroll in players list
- Makes the confirm button hide when the character is confirmed
- Changes title
> Character selection updates

- client/Assets/Prefabs/Camera/CameraUI.prefab
- client/Assets/Scripts/CustomInputManager.cs
- client/Assets/Scripts/CustomLevelManager.cs
Blank images are being displayed before adjusting the image of the buttons.
> Blank button images

- client/Assets/Prefabs/Camera/CameraUI.prefab
- client/Assets/Prefabs/UI/LobbyItem.prefab
- client/Assets/Scripts/UI/LobbiesListItem.cs
Lobby box is disabled for 2 seconds once its selected, to prevent spam and therefore multiply joins. 
This is a temporary solutions.
> Disabled lobby items on click

- client/Assets/Scripts/Messages.pb.cs
- messages.proto
- server/lib/dark_worlds_server/communication/messages.pb.ex
- server/lib/dark_worlds_server/communication/proto_transform.ex
- server/load_test/lib/load_test/communication/messages.pb.ex
- server/native/gamestate/src/game.rs
- server/native/gamestate/src/player.rs
> Gh 769 reduce cooldown while DoS is active

- docs/src/SUMMARY.md
- docs/src/add_documentation.md
Add a section to the docs on how to add new documentation to it.
closes #756
> How to add docs section

- client/Assets/Prefabs/Camera/CameraUI.prefab
This PR changes inputs position and size, based on issue #777 . Build it and test it on phone
> Change input size and position

- client/Assets/Prefabs/SkillRange.prefab
Remove mesh collider from skill range prefab
> [HOTFIX] Remove mesh collider from prefab 

- client/Assets/Scripts/Utils/Utils.cs
> Fix Utils errors on reconnect

- client/Assets/Prefabs/Camera/CameraUI.prefab
Change settings button to be activated on click not on hover
closes #741
> Change settings button input type

- client/Assets/Prefabs/Characters/Uma.prefab
> Bug fixes for Uma prefab

- client/Assets/Prefabs/UI/ErrorCanvas.prefab
- client/Assets/Scripts/LobbyConnection.cs
- client/Assets/Scripts/UI/Errors.cs
- server/lib/dark_worlds_server_web/controllers/lobby_controller.ex
Closes #674 
When the server and client versions do not match, a warning is shown after trying to join a lobby, create a new game or a quickgame.
> Warning about mismatching client and server hashes

- client/Assets/ScriptableObjects/Skills/DAgna/DAgna_Scherzo.asset
- client/Assets/ScriptableObjects/Skills/DAgna/DAgna_Skill1.asset
- client/Assets/ScriptableObjects/Skills/DAgna/DAgna_Skill2.asset
- client/Assets/ScriptableObjects/Skills/DAgna/DAgna_Skill3.asset
- client/Assets/ScriptableObjects/Skills/DAgna/DAgna_Skill4.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Aimshot.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Basic.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Dash.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Denial.asset
- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Multishot.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Fiery.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Leap.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Melee.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Rage.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Roll.asset
- client/Assets/ScriptableObjects/Skills/Uma/Uma_Skill1.asset
- client/Assets/ScriptableObjects/Skills/Uma/Uma_Skill2.asset
- client/Assets/ScriptableObjects/Skills/Uma/Uma_Skill3.asset
- client/Assets/ScriptableObjects/Skills/Uma/Uma_Skill4.asset
- client/Assets/ScriptableObjects/Skills/Uma/Uma_SkillBasic.asset
- client/Assets/Scripts/Battle.cs
- client/Assets/Scripts/CustomInputManager.cs
- client/Assets/Scripts/Skills/SkillInfo.cs
This PR solves issue #742 .
If a skill base cooldown is less than 1000ms it doesn't show a cooldown.
To test this:
- Pick any character
- Use a basic skill (that should not show a cooldown)
- Use any other skill (that should show a cooldown)
> Cooldown display

- client/Assets/Scripts/Battle.cs
> Out of area Hotfix

- client/Assets/Scripts/InputText.cs
- client/Assets/Scripts/LobbyConnection.cs
- client/Assets/Scripts/SelectServerIP.cs
- client/Assets/Scripts/ServersListHandler.cs
- client/Assets/Scripts/SocketConnectionManager.cs
Closes #916 
Change default server from Localhost to Brazil, to avoid getting the "lost connection" pop up when opening the game from a mobile device.
Also, several variable and attributes names that were in snake_case were changed to camelCase to follow C# naming conventions
> Change default server from Localhost to Brazil

- client/Assets/Prefabs/CharacterBase.prefab
- client/Assets/Prefabs/Characters/DAgna.prefab
- client/Assets/Prefabs/Characters/H4ck.prefab
- client/Assets/Prefabs/Characters/Muflus.prefab
- client/Assets/Prefabs/Characters/Uma.prefab
- client/Assets/Prefabs/Feedbacks/FeedbackContainer.prefab
- client/Assets/Prefabs/Feedbacks/States/Slowed.prefab
- client/Assets/Prefabs/PlayerBot.prefab
The FeedbackContainer component was missing in the CharacterBase prefab.
> Fix missing prefab in CharacterBase

- client/Assets/Prefabs/CharacterBase.prefab
- client/Assets/Prefabs/Characters/DAgna.prefab
- client/Assets/Prefabs/Characters/H4ck.prefab
- client/Assets/Prefabs/Characters/Muflus.prefab
- client/Assets/Prefabs/Characters/Uma.prefab
- client/Assets/Prefabs/Feedbacks/FeedbackContainer.prefab
- client/Assets/Prefabs/Feedbacks/States/Slowed.prefab
- client/Assets/Prefabs/Managers/BattleManager.prefab
- client/Assets/Prefabs/PlayerBot.prefab
- client/Assets/Scripts/Battle.cs
- client/Assets/Scripts/CustomLevelManager.cs
- client/Assets/Scripts/UI/KillFeedManager.cs
- client/Assets/Scripts/Utils/Utils.cs
closes #857 
If we have 3 players.
Player2 kills Players1, Player1 will spectate Player2.
Player3 kills player2, Player2 and Player1 will spectate Player3
> Spectate killer on death

- server/Makefile
> Add engine dependency update to makefile

- client/Assets/StreamingAssets/Characters.json
> Lock dagna in the Character Selection screen

- server/lib/dark_worlds_server/engine/player_tracker.ex
- server/lib/dark_worlds_server/engine/runner.ex
Part of #786 
- Remove player from game tracking after death
- Disable single player mode after spawning bots
> Reconnect improvements

- client/Assets/Scripts/SelectServerIP.cs
Trims the start and end of the select server custom input in the lobby selection screen.
Closes #940
> Trim custom server address.

- client/Assets/Scripts/CharacterBase.cs
- client/Assets/VisualEffects/vfxgraph_Spawn.vfx
Desactivate spawn VFX after the first time it is played.
closes #982
> Fix spawn VFX 

- client/Assets/Prefabs/Camera/CameraUI.prefab
- client/Assets/Prefabs/Camera/TitleScreenCameraUI.prefab
- client/Assets/Prefabs/UI/KillFeed.prefab
This PR fixes bugs the team noticed during one play test. Check:
- Exit buttons does no longer overlay with the settings screen. To test this create a match, die but don't be the last one to die. I tried this with bots. Enter Spectate mode and open the settings screen. 
- The sprite needed in title screen was restored
- KillFeed text was changed to uppercase and the font was also changed to the proper one
> UI Bug fixes

- README.md
To help onboard new teammembers, especially now that there's rotations.
> Update README with environment suggestions

- client/Assets/Scripts/Battle.cs
- client/Assets/Scripts/CustomLevelManager.cs
Problem:
Bots don't have animations because they are created in the middle of the game. So, when they spawn, they don't have related skills in Unity.
Solution:
Adding the skills to the bot when spawned.
> Fix bots animation

- README.md
Add some documentation for the setup of Unity.
> Add Unity setup documentation

- client/Assets/Scripts/CustomLevelManager.cs
- client/Assets/Scripts/Skills/Skill.cs
- server/lib/dark_worlds_server/communication.ex
- server/lib/dark_worlds_server/communication/proto_transform.ex
- server/lib/dark_worlds_server/engine/engine_runner.ex
- server/lib/dark_worlds_server_web/websockets/play_websocket.ex
Fix basic attacks using the new flow, also the direction when a player attacks.
> New flow basic attacks

- client/Assets/Models/LICENSE.md
> Add CC License

- client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
In Main screen you can't click the left side of the select server button because it gets overlapped with the model section
I rearrange the layers to fix the issue
> Select Server Button fix

- README.md
organize the four character images in a grid so that they occupy the space better, instead of being in a long column with too much blank space on the right
> organize images in a grid

- client/Assets/Graphy - Ultimate Stats Monitor/Graphy_CustomizationScene.unitypackage.meta
> Removed unnecessary file

- server/priv/config.json
> improve players balance

- client/Assets/Packages/Google.Protobuf.3.24.3.meta
- client/Assets/Scripts/DevLobbyConnection.cs
- client/Assets/Scripts/LobbyConnection.cs
- client/Assets/Scripts/Messages.pb.cs
- client/Assets/Scripts/SocketConnectionManager.cs
- communication/messages.proto
> Remove unused messages

- client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
- client/Assets/Scripts/SelectServerIP.cs
The server domain names changed so we need to point to the new urls
- Change the default server url
- Change the urls from the server options in the main screen
Waiting for servers to be configured to test
No tests added
> update server urls

- client/Assets/Animations/Muflus/MuflusController.controller
Although it can work on its own, it is intended to work with [this](https://github.com/lambdaclass/game_backend/pull/93) backend PR.
> Increased Muflus walking and idle speed

- client/Assets/Scripts/Battle.cs
> execute feedback if not executing other

- client/Assets/Prefabs/Camera/CameraUI.prefab
- client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
- client/Assets/Scripts/SelectServerIP.cs
The servers' URLs were outdated.
Change "myrra" to "mirra" in Brazil and Servers URLs.
> Fix servers URLs

- client/Assets/Scripts/Battle.cs
- client/Assets/Scripts/CharacterFeedbackManager.cs
- client/Assets/Scripts/ClientPrediction.cs
- client/Assets/Scripts/CustomLevelManager.cs
- client/Assets/Scripts/EventsBuffer.cs
- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/Messages.pb.cs
- client/Assets/Scripts/Utils/Utils.cs
- messages.proto
> Uncomment functions

- client/Assets/Scripts/Battle.cs
- client/Assets/Scripts/ClientPrediction.cs
- client/Assets/Scripts/EventsBuffer.cs
- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/Messages.pb.cs
- client/Assets/Scripts/PlayerControls.cs
- messages.proto
> Add client prediction

- client/Assets/Prefabs/ServersOptions.prefab
Fix wrong spelling of ip in europe and brazil
Changed the prefab that contains the ip addresses
> Fix brasil and europe ips

- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/PingCounter.cs
> enable ping message

- client/Assets/Scripts/Battle.cs
- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/Messages.pb.cs
- messages.proto
> add projectiles behaviour

- client/Assets/SpriteAtlas/InGameUI.spriteatlas
- client/Assets/SpriteAtlas/PrepareForBattle.spriteatlas
sprite atlas files were modified when starting a match
I added them
> Spriteatlas files

- client/Assets/Scripts/CustomLevelManager.cs
- client/Assets/Scripts/UI/EndGame/EndGameManager.cs
Closes #1359 
Fix Death splash with new backend integration
- Fix missing model
- Fix ranking
- Refactor character creation. ( Removed repeated code)
> Fix endgame rankings and models

- client/Assets/Scripts/Messages.pb.cs
- messages.proto
> stamina first iteration

- client/Assets/Scripts/ServerConnection.cs
> allow select character

- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/ServerConnection.cs
The previous IP doesn't work anymore.
> add loadtest server ip

- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Denial.asset
Change button type to Direction
> fix button type

- client/Assets/Prefabs/Camera/TitleScreenCameraUI.prefab
Set player name pop up "save" button was missing its sprite
This PR restores it
> Restore sprite to button

- client/Assets/Scripts/UI/PrepareForBattleAnimations.cs
Closes #1384 
With the integrations of the players initial position the cinematic got broken
The fix was to replace the front end player position with the back end position since they initially spawn and then move to the back end position.
Start a game and it should look smooth again
> Prepare for battle cinematic fix

- client/Assets/Prefabs/ServersOptions.prefab
- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/ServerConnection.cs
> Change ips to dns urls

- client/Assets/Scripts/Battle.cs
Closes  #1406
Various method in Battle.cs can we improved. This is one of them.
- Remove unused variables inside the method
- Simplify `playerControls` getComponent call to 1
- GetCharacter instead of GameObject.
Game should be working as always.
> Refactor SendPlayerMovement method in Battle.cs

- client/Assets/Scripts/GameServerConnectionManager.cs
Improve `GameServerConnectionManager`
Move the  `IsGameCreated` co routine from Updare method to Start
The method includes a `yield return new WaitUntil(() => !String.IsNullOrEmpty(SessionParameters.GameId));` so it is not necessary to having it in the Update method. It will start wait for the condition and then `ConnectToSession` which calls `OnWebSocketMessage` and starts listen to messages.
Without this change we are calling the co-routine `IsGameCreated` each frame.
To test it you can add a Log inside the `IsGameCreated` and `OnWebSocketMessage` Update message and see how many times it is called.
Then change the Coroutine back to the Update method and see the logs again.
> Improve GameServerConnectionManager

- client/Assets/Scripts/Battle.cs
The projectiles were not disappearing after colliding with a player
> Restore if on projectile collide function

- client/Assets/Prefabs/Projectiles/HackMultishot.prefab
- client/Assets/Prefabs/Projectiles/HackSlingshot.prefab
- client/Assets/Prefabs/Projectiles/ValtimerProjectile.prefab
Remove colliders in all the projectiles
> Remove collider in projectiles

- client/Assets/Scripts/Messages.pb.cs
- messages.proto
Client update for https://github.com/lambdaclass/mirra_backend/pull/314
> Receive skill configuration info

- client/Assets/Scripts/SelectServerIP.cs
We need to select US server by default
> add US as default server

- client/Assets/Prefabs/Camera/CameraUI.prefab
Closes #1502 
The game was throwing a reference error
Fixed both sfx and music toggle buttons
Start a game, go to settings and try using the sfx and music buttons
> Fix toggle audio references

- client/Assets/Scripts/ClientPrediction.cs
- client/Assets/Scripts/CustomLevelManager.cs
- client/Assets/Scripts/PlayerControls.cs
You will find the movement more smoothly (not robotic for the others and without the threshold movement for you).
Also, this PR fix the bug at the beginning of the game.
> Fix client prediction starting position

- client/Assets/Prefabs/Characters/Uma.prefab
- client/Assets/Scripts/CharacterFeedbackManager.cs
Closes #1524 
Souls was not disappearing in Uma ultimate
Add a list of vfx to disappear if the characters allow invisibility
Disclaimer: I could not use MMCondition with the list to display only if the character has vfx to disappear. 
Select 2 uma, the enemy should disappear complety. Your uma no changes should be displayed.
> Disappear souls in Uma

- client/Assets/Prefabs/Maps/Araban.prefab
- client/Assets/Prefabs/VisualEffects/Sand_Storm.prefab
- client/Assets/Prefabs/VisualEffects/Sand_Storm.prefab.meta
- client/Assets/Shaders/Vfx/Shader_Sand_Flow_VFX.shadergraph
- client/Assets/Shaders/Vfx/Shader_Sand_Flow_VFX.shadergraph.meta
- client/Assets/VFX-Tools/PIngle_VFX/Textures/T_Curl_Noises_01_sRGB.png.meta
- client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_SandStorm.vfx
- client/Assets/VFX-Tools/PIngle_VFX/VFXGraphs/vfxgrpah_SandStorm.vfx.meta
Closes #1550 
Add sand storm vfx to araban map
Add sand storm prefab with vfx.
> Add sand storm

- client/Assets/Prefabs/Camera/CharacterInfoCameraUI.prefab
- client/Assets/Prefabs/Camera/MainScreenCameraUI.prefab
- client/Assets/Prefabs/Camera/ModelCamera.prefab
- client/Assets/Scripts/UI/ButtonAnimationsMMTouchButton.cs
- client/Assets/Scripts/UI/ModelLink.cs
- client/Assets/Scripts/UI/ModelLink.cs.meta
- client/Assets/Scripts/UI/RotateUIModel.cs
Closes #1397
Closes #1605
Closes #1604 
Closes #1475 
Bugs in main:
- Rotation speed was too high
- Two ways of rendering the models in the UI (one in main and the other in character info) where used instead of one prefab. This resulted in two UX. mainly noticeable in the rotation feature. In main the rotation was within the character and in character info the rotation could be trigger from the sides
- When the user pressed the character, then dragged the finger but for the release of it they returned to the original position the link would trigger. This is not ideal behavior.
Solved issues:
- Rotation speed was adjusted
- Now we have 1 prefab used to render UI models
- The code was refactored to have a clean and readable code
In addition:
- Adjusted the main screen and characters info …
> UI character implementation

- client/Assets/Scripts/UI/Settings/ToggleAudio.cs
- client/Assets/Scripts/UI/VolumeController.cs
Closes #1066 
Reduce volumen, recreate the issue made in 
https://github.com/lambdaclass/curse_of_mirra/commit/8563a30dab64fdd978377b637d73b5bbfbb00b97
Create vars for volume.
The volumen should be lower.
> Reduce volume

- client/Assets/Scripts/SelectServerIP.cs
Add server selection depending if it is a mobile build or the unity editor.
Make a build, Brasil should be selected as server and when playing in the PC localhost should be selected.
> Select server QoL

- client/Assets/Prefabs/ServersOptions.prefab
- client/Assets/Scripts/SelectServerIP.cs
We changed the server urls.
Changed brazil and Europe URLs
You can open unity and play in those servers.
No tests added.
> Fix europe and arena urls

- client/Assets/Scripts/Messages.pb.cs
- messages.proto
The pools were failing after the merge of the collisionable pr since we didn't update the messages.proto file on the game client and it was changed in the backend
> Add pools to gamestate

- client/Assets/Scripts/UI/CharacterInfoManager.cs
- client/Assets/Scripts/UI/TitleScreenController.cs
Minor QoL improvement, save character name in the client after selected
- Save the character name in the playerPrefs
- If not null selected the character save or Muflus for default.
> Save selected character on client

- client/Assets/Animations/Valtimer/ValtimerController.controller
- client/Assets/Prefabs/Projectiles/Antimatter_trail.prefab
- client/Assets/Prefabs/Projectiles/ValtimerAntimatterFeedback.prefab
- client/Assets/Prefabs/Projectiles/Valtimer_Animatter_Projectile.prefab
- client/Assets/Prefabs/VisualEffects/Valtimer_Antimatter_Casting.prefab
- client/Assets/ScriptableObjects/Skills/Valtimer/Valtimer_Antimatter.asset
Backend PR -> https://github.com/lambdaclass/mirra_backend/pull/461
Valtimer needed adjustments in client
This PR does that
> Balance valtimer

- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Flash.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Rampage.asset
- client/Assets/ScriptableObjects/Skills/Uma/Uma_Sneak.asset
- client/Assets/ScriptableObjects/Skills/Valtimer/Valtimer_Antimatter.asset
- client/Assets/Scripts/Skills/SkillInfo.cs
Change Valtimer indicator to arrow and fix others indicators
Change indicators tu use hardcoded values when their do not have values from the backend.
Use each dash indicator and projectile indicators
> Set Valtimer cone to arrow and fix others indicators

- client/Assets/Scenes/CharacterInfo.unity
Lights in character info an main screen were different and affected the character models a lot
This PR fixes that. They are now the same in both
> Fix light config in Character Info

- client/Assets/Scripts/CharacterFeedbacks.cs
- client/Assets/Scripts/UI/CustomMMTouchJoystick.cs
Closes #1692
Haptic feedback needed to be improved and also add it when dealing damage.
Improve haptic when canceling skill
Add haptic when dealing damage.
Deal damage, receive damage,  heal and cancel skills.
> Improve haaptic Feedback

- client/Assets/ScriptableObjects/Skills/H4ck/H4ck_Flash.asset
- client/Assets/ScriptableObjects/Skills/Muflus/Muflus_Rampage.asset
- client/Assets/ScriptableObjects/Skills/Uma/Uma_Sneak.asset
depends on https://github.com/lambdaclass/mirra_backend/pull/526
> faster dash anims

- client/Assets/Scripts/Messages.pb.cs
- messages.proto
Closes #1768 
Add missing messages in the client
- Modified the `messages.proto` 
Build the game and test it with brazil or europe
> [GH-1768] - Add missing messages

- client/Assets/Scripts/Messages.pb.cs
- messages.proto
This pr changes the messages.proto to be the same as [This backend pr](https://github.com/lambdaclass/mirra_backend/pull/592) and they should me merged together
> proto-change-from-backend-pr-592 

- client/Assets/Scripts/Messages.pb.cs
- messages.proto
> Add bounties protos

- client/Assets/Prefabs/Camera/CameraUI.prefab
- client/Assets/Prefabs/UI/BattleSettingsSplash.prefab
- client/Assets/Scenes/Battle.unity
- client/Assets/Scripts/Battle.cs
- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/Messages.pb.cs
- client/Assets/Scripts/UI/Settings/ToggleButton.cs
- messages.proto
> [!IMPORTANT]  
> This PR must be merged along with https://github.com/lambdaclass/mirra_backend/pull/688
Closes #1824 
We need several tools for testing purposes. This is one of them.
Deactivating the zone, we can last longer.
- [Add zone toggle button](https://github.com/lambdaclass/champions_of_mirra/pull/1827/commits/21155d4fc5c7a233c7eff98f801353db535380f3)
- [Add new ToggleZone protobuf message](https://github.com/lambdaclass/champions_of_mirra/pull/1827/commits/83e6534d0baf58939755f8606c0e9075c009f993)
- [Send ToggleZone message when interacting with UI button](https://github.com/lambdaclass/champions_of_mirra/pull/1827/commits/61758ff0c550f8211991cc04e49cecb189068a5a)
- [Add text below zone button to show if its on/off](https://github.com/lambdaclass/champions_of_mirra/pull/1827/c …
> [GH-1824] Add zone toggle button

- client/Assets/Scenes/TitleScreen.unity
- client/Assets/Scripts/GameServerConnectionManager.cs
- client/Assets/Scripts/GoogleSignIn/GoogleSignInController.cs
- client/Assets/Scripts/GuestSignIn.meta
- client/Assets/Scripts/GuestSignIn/GuestSignInController.cs
- client/Assets/Scripts/GuestSignIn/GuestSignInController.cs.meta
- client/Assets/Scripts/ServerConnection.cs
- client/Assets/Scripts/Utils/ServerUtils.cs
**NOTE: If you login (guest or google) and then reset the DB the login will stop working cause the user can't be found. You will need to either clear the app data or clear `PlayerPrefs` in Unity**
Test together with https://github.com/lambdaclass/mirra_backend/pull/665 by playing games and seeing the match results stored
> Authentication with JWT
